:pencil: (CONTRIBUTING.md) updating chart-testing to v3.13.0 from v2.5.0
fixing Chart.yaml apiVersion error due to helm v3
Using v2.5.0 with Chart.yaml using apiVersion v2:
Error: apiVersion 'v2' is not valid. The value must be "v1"

Signed-off-by: Llyth <6819575+Llyth@users.noreply.github.com>